name: academic_master
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  analyzer: ^2.5.0
  animations: ^2.0.1
  another_flushbar: ^1.10.24
  auto_route: ^3.2.0
  cached_network_image: ^3.1.0
  circular_reveal_animation: ^2.0.0
  cloud_firestore: ^2.5.3
  dartdap: ^0.6.1
  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.3
  file_picker: ^4.1.3
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  firebase_storage: ^10.0.5
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_cached_pdfview: ^0.4.0-nullsafety
  flutter_feather_icons: ^2.0.0+1
  flutter_hooks: ^0.18.0
  flutter_screenutil: ^5.0.0+2
  flutter_signin_button: ^2.0.0-nullsafety.0
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.22.0
  flutter_zoom_drawer: ^2.1.1
  freezed_annotation: ^0.15.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.1
  http: ^0.13.4
  injectable: ^1.5.0
  json_annotation: ^4.1.0
  kt_dart: ^0.9.1
  line_icons: ^2.0.1
  loading_indicator: ^3.0.2
  lottie: ^1.2.1
  modal_bottom_sheet: ^2.0.0
  nil: ^1.1.1
  path_provider: ^2.0.5
  persistent_bottom_nav_bar: ^4.0.2
  flutter_swipe_action_cell: ^2.1.5
  provider: ^6.0.1
  responsive_framework: ^0.1.4
  rxdart: ^0.27.2
  shared_preferences: ^2.0.8
  selectable_autolink_text: ^2.3.0
  share: ^2.0.4
  url_launcher: ^6.0.12
  uuid: ^3.0.5
  webview_flutter: ^2.1.1

dev_dependencies:
  auto_route_generator: ^3.2.0
  build_runner: ^2.1.7
  flutter_test:

    sdk: flutter
  freezed: ^0.15.0+1
  injectable_generator: ^1.5.2
  json_serializable: ^5.0.2
  lint: ^1.7.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottiefiles/
    - assets/icons/

  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/circular.otf
    - family: Circular_Bold
      fonts:
        - asset: assets/fonts/CircularStdBold.otf
    - family: Circular_Medium
      fonts:
        - asset: assets/fonts/CircularStdMedium.otf
